import queue
import threading
import itertools
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

# =============================================================================
# Exceptions
# =============================================================================

class EventEngineError(Exception):
    """Base class for all Event Engine exceptions."""
    pass

class QueueStarvationError(EventEngineError):
    """Raised when the event queue starves (no events available within timeout)."""
    pass

class EventValidationError(EventEngineError):
    """Raised when an event fails validation during instantiation."""
    pass

class TemporalSequenceViolationError(EventEngineError):
    """Raised when a historical event arrives out-of-order temporally."""
    pass

class DuplicateOrderIdError(EventValidationError):
    """Raised when an order with an already seen ID is submitted."""
    pass


# =============================================================================
# Enums
# =============================================================================

class BarType(Enum):
    TICK = "TICK"
    BAR_1M = "1M"
    BAR_5M = "5M"
    BAR_1H = "1H"
    BAR_1D = "1D"

class SignalDirection(Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    EXIT = "EXIT"

class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    ICEBERG = "ICEBERG"

class OrderDirection(Enum):
    BUY = "BUY"
    SELL = "SELL"

class TimeInForce(Enum):
    GTC = "GTC"
    IOC = "IOC"
    FOK = "FOK"


# =============================================================================
# Core Event Data Objects
# =============================================================================

@dataclass(slots=True, frozen=True)
class Event:
    """
    Abstract base class for all events.

    Time complexity: O(1) for instantiation.
    Memory overhead: Very low (~48 bytes) due to slots=True and frozen=True.
    """
    timestamp: int  # UTC nanoseconds

    def __post_init__(self) -> None:
        if not isinstance(self.timestamp, int) or self.timestamp < 0:
            raise EventValidationError("timestamp must be a non-negative integer (UTC nanoseconds).")

@dataclass(slots=True, frozen=True)
class MarketEvent(Event):
    """
    Market data event for ticks or bars.

    Time complexity: O(1)
    Memory overhead: ~120 bytes per instance.
    """
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    bid_ask_spread: float
    bar_type: BarType

    def __post_init__(self) -> None:
        Event.__post_init__(self)
        if not self.symbol:
            raise EventValidationError("symbol must not be empty.")
        if self.high < self.low:
            raise EventValidationError("high cannot be less than low.")
        if self.volume < 0:
            raise EventValidationError("volume cannot be negative.")
        if self.bid_ask_spread < 0:
            raise EventValidationError("bid_ask_spread cannot be negative.")

@dataclass(slots=True, frozen=True)
class SignalEvent(Event):
    """
    Trading signal event generated by strategies.

    Time complexity: O(1)
    Memory overhead: ~104 bytes per instance.
    """
    symbol: str
    signal_type: SignalDirection
    strength: float
    target_quantity: int
    suggested_stop_loss: Optional[float] = None
    suggested_take_profit: Optional[float] = None

    def __post_init__(self) -> None:
        Event.__post_init__(self)
        if not self.symbol:
            raise EventValidationError("symbol must not be empty.")
        if not isinstance(self.signal_type, SignalDirection):
            raise EventValidationError("signal_type must be a SignalDirection.")
        if not (0.0 <= self.strength <= 1.0):
            raise EventValidationError("strength must be between 0.0 and 1.0.")
        if self.target_quantity < 0:
            raise EventValidationError("target_quantity cannot be negative.")
        if self.suggested_stop_loss is not None and self.suggested_stop_loss < 0:
            raise EventValidationError("suggested_stop_loss cannot be negative.")
        if self.suggested_take_profit is not None and self.suggested_take_profit < 0:
            raise EventValidationError("suggested_take_profit cannot be negative.")

@dataclass(slots=True, frozen=True)
class OrderEvent(Event):
    """
    Order execution intent event.

    Time complexity: O(1)
    Memory overhead: ~120 bytes per instance.
    """
    symbol: str
    order_type: OrderType
    direction: OrderDirection
    quantity: int
    order_id: str
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    time_in_force: TimeInForce = TimeInForce.GTC

    def __post_init__(self) -> None:
        Event.__post_init__(self)
        if not self.symbol:
            raise EventValidationError("symbol must not be empty.")
        if not self.order_id:
            raise EventValidationError("order_id must not be empty.")
        if not isinstance(self.order_type, OrderType):
            raise EventValidationError("order_type must be an OrderType.")
        if not isinstance(self.direction, OrderDirection):
            raise EventValidationError("direction must be an OrderDirection.")
        if self.quantity <= 0:
            raise EventValidationError("quantity must be positive.")
        if self.order_type == OrderType.LIMIT and self.limit_price is None:
            raise EventValidationError("LIMIT orders require a limit_price.")
        if self.order_type == OrderType.STOP and self.stop_price is None:
            raise EventValidationError("STOP orders require a stop_price.")
        if self.limit_price is not None and self.limit_price < 0:
            raise EventValidationError("limit_price cannot be negative.")
        if self.stop_price is not None and self.stop_price < 0:
            raise EventValidationError("stop_price cannot be negative.")

@dataclass(slots=True, frozen=True)
class FillEvent(Event):
    """
    Execution confirmation event.

    Time complexity: O(1)
    Memory overhead: ~136 bytes per instance.
    """
    symbol: str
    exchange: str
    quantity_filled: int
    fill_price: float
    direction: OrderDirection
    commission_fee: float
    slippage_cost: float
    impact_cost: float
    order_id: str

    def __post_init__(self) -> None:
        Event.__post_init__(self)
        if not self.symbol:
            raise EventValidationError("symbol must not be empty.")
        if not self.exchange:
            raise EventValidationError("exchange must not be empty.")
        if not self.order_id:
            raise EventValidationError("order_id must not be empty.")
        if not isinstance(self.direction, OrderDirection):
            raise EventValidationError("direction must be an OrderDirection.")
        if self.quantity_filled < 0:
            raise EventValidationError("quantity_filled cannot be negative.")
        if self.fill_price < 0:
            raise EventValidationError("fill_price cannot be negative.")
        if self.commission_fee < 0:
            raise EventValidationError("commission_fee cannot be negative.")
        if self.slippage_cost < 0:
            raise EventValidationError("slippage_cost cannot be negative.")
        if self.impact_cost < 0:
            raise EventValidationError("impact_cost cannot be negative.")


# =============================================================================
# Event Queue Infrastructure
# =============================================================================

@dataclass(order=True)
class _QueueItem:
    """Internal wrapper for priority queue ordering."""
    timestamp: int
    seqno: int
    event: Event = field(compare=False)

class EventQueue:
    """
    Thread-safe, priority-aware queue for Event objects.
    Ensures that events are processed strictly in temporal order (by timestamp).

    Time complexity:
    - put(): O(log N) due to heap push
    - get(): O(log N) due to heap pop
    """
    def __init__(self) -> None:
        self._queue: "queue.PriorityQueue[_QueueItem]" = queue.PriorityQueue()
        self._seq = itertools.count()
        self._last_timestamp: Optional[int] = None
        self._known_order_ids: set[str] = set()
        self._lock = threading.RLock()

    def put(self, event: Event) -> None:
        """
        Puts an event onto the queue.
        Validates temporal sequencing and raises an error if an event is older than
        the most recently processed event.
        Also validates that order_ids are unique.
        """
        if not isinstance(event, Event):
            raise EventValidationError(f"Expected an Event subclass, got {type(event).__name__}")

        with self._lock:
            # Temporal sequence validation against dequeued events
            if self._last_timestamp is not None and event.timestamp < self._last_timestamp:
                raise TemporalSequenceViolationError(
                    f"Event timestamp {event.timestamp} is older than the last "
                    f"processed timestamp {self._last_timestamp}."
                )

            # Duplicate order ID validation
            if isinstance(event, OrderEvent):
                if event.order_id in self._known_order_ids:
                    raise DuplicateOrderIdError(
                        f"Order ID {event.order_id} has already been queued."
                    )
                self._known_order_ids.add(event.order_id)

            item = _QueueItem(
                timestamp=event.timestamp,
                seqno=next(self._seq),
                event=event
            )
            self._queue.put(item)

    def get(self, timeout: Optional[float] = None) -> Event:
        """
        Retrieves the next event from the queue.
        Raises QueueStarvationError if no events are available within the timeout.
        """
        try:
            item = self._queue.get(timeout=timeout)
        except queue.Empty:
            raise QueueStarvationError("No events available in the queue.")

        with self._lock:
            # Re-verify temporal sequencing against dequeued events
            if self._last_timestamp is not None and item.event.timestamp < self._last_timestamp:
                raise TemporalSequenceViolationError(
                    f"Dequeued event timestamp {item.event.timestamp} is older than "
                    f"last processed timestamp {self._last_timestamp}."
                )
            self._last_timestamp = item.event.timestamp

        return item.event

    def empty(self) -> bool:
        """Returns True if the queue is empty, False otherwise."""
        return self._queue.empty()

    def qsize(self) -> int:
        """Returns the approximate size of the queue."""
        return self._queue.qsize()

# =============================================================================
# Unit Tests (pytest)
# =============================================================================

import pytest

def test_market_event_validation():
    # Valid MarketEvent
    event = MarketEvent(
        timestamp=1625097600000000000,
        symbol="AAPL",
        open=150.0,
        high=152.0,
        low=149.0,
        close=151.0,
        volume=1000.0,
        bid_ask_spread=0.01,
        bar_type=BarType.TICK
    )
    assert event.symbol == "AAPL"

    # Invalid: negative volume
    with pytest.raises(EventValidationError):
        MarketEvent(
            timestamp=1625097600000000000,
            symbol="AAPL",
            open=150.0,
            high=152.0,
            low=149.0,
            close=151.0,
            volume=-10.0,
            bid_ask_spread=0.01,
            bar_type=BarType.TICK
        )

def test_signal_event_validation():
    event = SignalEvent(
        timestamp=1625097600000000000,
        symbol="MSFT",
        signal_type=SignalDirection.LONG,
        strength=0.8,
        target_quantity=100
    )
    assert event.strength == 0.8

    # Invalid: strength out of bounds
    with pytest.raises(EventValidationError):
        SignalEvent(
            timestamp=1625097600000000000,
            symbol="MSFT",
            signal_type=SignalDirection.LONG,
            strength=1.5,
            target_quantity=100
        )

def test_order_event_validation():
    event = OrderEvent(
        timestamp=1625097600000000000,
        symbol="TSLA",
        order_type=OrderType.LIMIT,
        direction=OrderDirection.BUY,
        quantity=50,
        order_id="ORD-001",
        limit_price=650.0
    )
    assert event.order_id == "ORD-001"

    # Invalid: missing limit_price for LIMIT order
    with pytest.raises(EventValidationError):
        OrderEvent(
            timestamp=1625097600000000000,
            symbol="TSLA",
            order_type=OrderType.LIMIT,
            direction=OrderDirection.BUY,
            quantity=50,
            order_id="ORD-002"
        )

def test_fill_event_validation():
    event = FillEvent(
        timestamp=1625097600000000000,
        symbol="TSLA",
        exchange="NASDAQ",
        quantity_filled=50,
        fill_price=650.0,
        direction=OrderDirection.BUY,
        commission_fee=1.50,
        slippage_cost=0.50,
        impact_cost=0.0,
        order_id="ORD-001"
    )
    assert event.quantity_filled == 50

    # Invalid: negative commission fee
    with pytest.raises(EventValidationError):
        FillEvent(
            timestamp=1625097600000000000,
            symbol="TSLA",
            exchange="NASDAQ",
            quantity_filled=50,
            fill_price=650.0,
            direction=OrderDirection.BUY,
            commission_fee=-1.50,
            slippage_cost=0.50,
            impact_cost=0.0,
            order_id="ORD-001"
        )

def test_event_queue_temporal_ordering():
    eq = EventQueue()

    # Create events out of chronological order
    event1 = MarketEvent(100, "AAPL", 1.0, 1.0, 1.0, 1.0, 100, 0.01, BarType.TICK)
    event3 = MarketEvent(300, "AAPL", 1.0, 1.0, 1.0, 1.0, 100, 0.01, BarType.TICK)
    event2 = MarketEvent(200, "AAPL", 1.0, 1.0, 1.0, 1.0, 100, 0.01, BarType.TICK)

    # Enqueue them
    eq.put(event3)
    eq.put(event1)
    eq.put(event2)

    # They should come out in strict chronological order
    assert eq.get().timestamp == 100
    assert eq.get().timestamp == 200
    assert eq.get().timestamp == 300

def test_event_queue_temporal_violation():
    eq = EventQueue()

    event2 = MarketEvent(200, "AAPL", 1.0, 1.0, 1.0, 1.0, 100, 0.01, BarType.TICK)
    event1 = MarketEvent(100, "AAPL", 1.0, 1.0, 1.0, 1.0, 100, 0.01, BarType.TICK)

    eq.put(event2)
    # Process event2, advancing the queue's internal clock to 200
    eq.get()

    # Now trying to put event1 (timestamp 100) should raise a violation
    with pytest.raises(TemporalSequenceViolationError):
        eq.put(event1)

def test_event_queue_duplicate_order_id():
    eq = EventQueue()
    order1 = OrderEvent(
        timestamp=100, symbol="AAPL", order_type=OrderType.MARKET,
        direction=OrderDirection.BUY, quantity=10, order_id="ID1"
    )
    order2 = OrderEvent(
        timestamp=200, symbol="AAPL", order_type=OrderType.MARKET,
        direction=OrderDirection.BUY, quantity=20, order_id="ID1"
    )

    eq.put(order1)
    with pytest.raises(DuplicateOrderIdError):
        eq.put(order2)

def test_event_queue_starvation():
    eq = EventQueue()
    with pytest.raises(QueueStarvationError):
        eq.get(timeout=0.01)

if __name__ == "__main__":
    pytest.main(["-v", __file__])
